logger:
  output: "stdout"
  debug: false
  level: INFO
  add_caller: true
  caller_skip: 1

polarx:
  host: "pc-2ev75w4bn1748568x.rwlb.rds.aliyuncs.com"
  port: 3306
  user: "dev_root"
  password: "fbCyEZD!iB9c7JY"
  database: "solana_data"
  timeout: "10s"
  max_pool_size: 100
  max_idle_size: 30
  open_debug: false
  log_level: "silent"

kafka:
  brokers:
    - alikafka-pre-public-intl-sg-nnu47okt601-1-vpc.alikafka.aliyuncs.com:9094
    - alikafka-pre-public-intl-sg-nnu47okt601-2-vpc.alikafka.aliyuncs.com:9094
    - alikafka-pre-public-intl-sg-nnu47okt601-3-vpc.alikafka.aliyuncs.com:9094

  consumer:
    topics:
      - "test-solana-tx"
    group_id: "test-signal"
    assignor: "sticky"
    version: "2.6.2"
    client_id: "test-signal"
    enable_auto_commit: false
    enable_auto_store: false
    auto_commit_interval: 5000
    read_timeout: 3000
    security_protocol: "SASL_PLAINTEXT"
    sasl_username: "dev"
    sasl_password: "XdkPv8j092!Pjo0"
    sasl_mechanism: "PLAIN"